name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.12'
    - name: Build Docs
      run: cd vue-next-analysis
      run: npm install
      run: cd ..
      run: ls
      run: npm run build:docs
      shell: bash
